# x y [size] icon_png_path Label | command to run
# size is optional and uses pixels for the rendered icon size
40 40 48 icons/64x64/apps/terminal.png Terminal | foot
140 40 48 icons/64x64/devices/drive-harddisk.png Disk | thunar
240 40 48 icons/64x64/apps/cutemarked.png Vim | foot -e nvim
340 40 48 icons/64x64/apps/calc.png Calculator | galculator
440 40 48 icons/64x64/apps/calc.png Calculator2 | galculator
540 40 48 icons/64x64/devices/video-display.png Screen | sh launch_resolution.sh
